import mongoose, { Schema, models } from "mongoose";

/**
 * Schema for product colors (sub‑document)
 */
const ColorSchema = new Schema(
  {
    name: { type: String, required: true },
    value: { type: String, required: true, default: "#000000" },
  },
  { _id: false },
); // no separate `_id` for color objects

/**
 * Main Product Schema
 * Matches MostSellProductType interface
 */
const ProductSchema = new Schema(
  {
    // _id is auto-generated by Mongoose, but you can set it manually if needed
    name: {
      type: String,
      required: [true, "نام محصول الزامی است"],
      trim: true,
    },
    price: {
      type: Number,
      required: [true, "قیمت الزامی است"],
      min: [0, "قیمت نمی‌تواند منفی باشد"],
    },
    image: {
      type: [String],
      default: [],
      validate: {
        validator: (v: string[]) => v.length > 0,
        message: "حداقل یک تصویر الزامی است",
      },
    },
    category: {
      type: String,
      required: [true, "دسته‌بندی الزامی است"],
      trim: true,
    },
    size: { type: String, trim: true },
    material: { type: String, trim: true },
    colors: {
      type: [ColorSchema],
      default: [],
    },
    rating: {
      type: Number,
      default: 5,
      min: 0,
      max: 5,
    },
    reviews: {
      type: Number,
      default: 0,
      min: 0,
    },
    sold: {
      type: Number,
      default: 0,
      min: 0,
    },
    stock: {
      type: Number,
      required: [true, "موجودی الزامی است"],
      min: [0, "موجودی نمی‌تواند منفی باشد"],
    },
    discount: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },
    brand: { type: String, trim: true },
    description: { type: String, trim: true },
    dimensions: { type: String, trim: true },
    weight: { type: String, trim: true },
    careInstructions: { type: String, trim: true },
    features: { type: [String], default: [] },
    bedSize: { type: String, trim: true },
    frameType: { type: String, trim: true },
    assemblyRequired: { type: Boolean, default: false },
    warranty: { type: String, trim: true },
  },
  {
    timestamps: true, // adds `createdAt` and `updatedAt`
  },
);

// Avoid overwriting the model if it's already compiled
export default models.Product || mongoose.model("Product", ProductSchema);
