import type { Metadata } from "next";
import { iranYekan } from "@/lib/font";
import "./globals.css";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.ico", // path relative to /public
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='pe'
      dir='rtl'
      className={`${iranYekan.variable} h-full antialiased`}>
      <body className='min-h-full flex flex-col'>
        <main>
          <Header />
          <section>
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
