import {
  ShieldCheck,
  Truck,
  RotateCcw,
  Gem,
  Send,
  Phone,
  Mail,
  MapPin,
} from "lucide-react";
import { BsInstagram, BsFacebook } from "react-icons/bs";
export const CategotyMenu = [
  {
    title: "خانه",
    href: "/",
  },
  {
    title: "سرویس خواب مدرن",
    href: "/modern-bedroom-set",
  },
  {
    title: "سرویس خواب دو نفره",
    href: "/double-bedroom-set",
  },
  {
    title: "سرویس خواب یک نفره",
    href: "/single-bedroom-set",
  },
  {
    title: "سرویس خواب نوجوان",
    href: "/teen-bedroom-set",
  },
  {
    title: "سرویس خواب سلطنتی",
    href: "/royal-bedroom-set",
  },
];
export const whyTrustUs = [
  {
    icon: ShieldCheck,
    title: "ضمانت اصالت کالا",
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    icon: Truck,
    title: "ارسال رایگان",
    color: "text-blue-600",
    bg: "bg-blue-50",
  },
  {
    icon: RotateCcw,
    title: "بازگشت ۷ روزه",
    color: "text-amber-600",
    bg: "bg-amber-50",
  },
  {
    icon: Gem,
    title: "کیفیت تضمینی",
    color: "text-violet-600",
    bg: "bg-violet-50",
  },
];

export const categories = [
  {
    name: "مدرن",
    slug: "modern",
    image: "/images/categories/modern.jpg",
    href: "/modern-bedroom-set",
  },
  {
    name: "باکس‌دار",
    slug: "storage",
    image: "/images/categories/space.jpg",
    href: "/box-bedroom-set",
  },
  {
    name: "دو نفره",
    slug: "double",
    image: "/images/categories/double.jpg",
    href: "/double-bedroom-set",
  },
  {
    name: "یک نفره",
    slug: "single",
    image: "/images/categories/single.jpg",
    href: "/single-bedroom-set",
  },
  {
    name: "کودک / نوجوان",
    slug: "kids",
    image: "/images/categories/kid.jpg",
    href: "/kids-bedroom-set",
  },
  {
    name: "سلطنتی",
    slug: "classic",
    image: "/images/categories/kingdom.jpg",
    href: "/classic-bedroom-set",
  },
];

export const mostSellsProduct = [
  {
    id: 1,
    name: "سرویس روتختی دونفره مدل رویال",
    price: 3850000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "پنبه ۱۰۰٪",
    color: "سفید و طوسی",
    rating: 4.9,
    reviews: 148,
    sold: 620,
    stock: 18,
    discount: 10,
  },
  {
    id: 2,
    name: "سرویس روتختی یک‌نفره مدل آرام",
    price: 2450000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی",
    size: "یک‌نفره",
    material: "میکروفایبر",
    color: "آبی",
    rating: 4.8,
    reviews: 95,
    sold: 480,
    stock: 24,
    discount: 11,
  },
  {
    id: 3,
    name: "سرویس روتختی دونفره مدل کلاسیک",
    price: 4290000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "ساتن",
    color: "کرم",
    rating: 4.7,
    reviews: 132,
    sold: 530,
    stock: 15,
    discount: 13,
  },
  {
    id: 4,
    name: "سرویس روتختی سه‌بعدی مدل گلستان",
    price: 4650000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "پنبه و پلی‌استر",
    color: "سفید و صورتی",
    rating: 4.9,
    reviews: 176,
    sold: 710,
    stock: 12,
    discount: 8.4,
  },
  {
    id: 5,
    name: "سرویس روتختی هتلی مدل لوکس",
    price: 5190000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی",
    size: "کینگ",
    material: "پنبه هتلی",
    color: "سفید",
    rating: 5.0,
    reviews: 203,
    sold: 845,
    stock: 10,
    discount: 10,
  },
  {
    id: 6,
    name: "سرویس روتختی کودک مدل ستاره",
    price: 1890000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی کودک",
    size: "یک‌نفره",
    material: "پنبه نرم",
    color: "آبی آسمانی",
    rating: 4.8,
    reviews: 84,
    sold: 390,
    stock: 20,
    discount: 15.6,
  },
];

export const newestSellsProduct = [
  {
    id: 1,
    name: "سرویس روتختی دونفره مدل رویال",
    price: 3850000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "پنبه ۱۰۰٪",
    color: "سفید و طوسی",
    rating: 4.9,
    reviews: 148,
    sold: 620,
    stock: 18,
    discount: 10,
  },
  {
    id: 2,
    name: "سرویس روتختی یک‌نفره مدل آرام",
    price: 2450000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی",
    size: "یک‌نفره",
    material: "میکروفایبر",
    color: "آبی",
    rating: 4.8,
    reviews: 95,
    sold: 480,
    stock: 24,
    discount: 11,
  },
  {
    id: 3,
    name: "سرویس روتختی دونفره مدل کلاسیک",
    price: 4290000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "ساتن",
    color: "کرم",
    rating: 4.7,
    reviews: 132,
    sold: 530,
    stock: 15,
    discount: 13,
  },
  {
    id: 4,
    name: "سرویس روتختی سه‌بعدی مدل گلستان",
    price: 4650000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "پنبه و پلی‌استر",
    color: "سفید و صورتی",
    rating: 4.9,
    reviews: 176,
    sold: 710,
    stock: 12,
    discount: 8.4,
  },
  {
    id: 5,
    name: "سرویس روتختی هتلی مدل لوکس",
    price: 5190000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی",
    size: "کینگ",
    material: "پنبه هتلی",
    color: "سفید",
    rating: 5.0,
    reviews: 203,
    sold: 845,
    stock: 10,
    discount: 10,
  },
  {
    id: 6,
    name: "سرویس روتختی کودک مدل ستاره",
    price: 1890000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی کودک",
    size: "یک‌نفره",
    material: "پنبه نرم",
    color: "آبی آسمانی",
    rating: 4.8,
    reviews: 84,
    sold: 390,
    stock: 20,
    discount: 15.6,
  },
];

export const socialLinks = [
  {
    href: "#",
    icon: BsInstagram,
    label: "Instagram",
  },
  {
    href: "#",
    icon: Send,
    label: "Telegram",
  },
  {
    href: "#",
    icon: BsFacebook,
    label: "Facebook",
  },
];

export const footerQuickLinks = [
  {
    title: "صفحه اصلی",
    href: "/",
  },
  {
    title: "محصولات",
    href: "/products",
  },
  {
    title: "درباره ما",
    href: "/about",
  },
  {
    title: "تماس با ما",
    href: "/contact",
  },
];

export const footerContactInfo = [
  {
    icon: Phone,
    value: "0912 345 6789",
  },
  {
    icon: Mail,
    value: "info@example.com",
  },
  {
    icon: MapPin,
    value: "تهران، ایران",
    className: "items-start",
    iconClassName: "mt-1",
  },
];
