import { ShieldCheck, Truck, RotateCcw, Gem } from "lucide-react";

export const whyTrustUs = [
  {
    icon: ShieldCheck,
    title: "ضمانت اصالت کالا",
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    icon: Truck,
    title: "ارسال رایگان",
    color: "text-blue-600",
    bg: "bg-blue-50",
  },
  {
    icon: RotateCcw,
    title: "بازگشت ۷ روزه",
    color: "text-amber-600",
    bg: "bg-amber-50",
  },
  {
    icon: Gem,
    title: "کیفیت تضمینی",
    color: "text-violet-600",
    bg: "bg-violet-50",
  },
];

export const categories = [
  {
    name: "مدرن",
    slug: "modern",
    image: "/images/categories/modern.jfif",
  },
  {
    name: "باکس‌دار",
    slug: "storage",
    image: "/images/categories/space.jfif",
  },
  {
    name: "دو نفره",
    slug: "double",
    image: "/images/categories/double.jfif",
  },
  {
    name: "یک نفره",
    slug: "single",
    image: "/images/categories/single.jfif",
  },
  {
    name: "کودک / نوجوان",
    slug: "kids",
    image: "/images/categories/kid.jfif",
  },
  {
    name: "سلطنتی",
    slug: "classic",
    image: "/images/categories/kingdom.jfif",
  },
];

export const mostSellsProduct = [
  {
    id: 1,
    name: "سرویس روتختی دونفره مدل رویال",
    price: 3850000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "پنبه ۱۰۰٪",
    color: "سفید و طوسی",
    rating: 4.9,
    reviews: 148,
    sold: 620,
    stock: 18,
    discount: 10,
  },
  {
    id: 2,
    name: "سرویس روتختی یک‌نفره مدل آرام",
    price: 2450000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی",
    size: "یک‌نفره",
    material: "میکروفایبر",
    color: "آبی",
    rating: 4.8,
    reviews: 95,
    sold: 480,
    stock: 24,
    discount: 11,
  },
  {
    id: 3,
    name: "سرویس روتختی دونفره مدل کلاسیک",
    price: 4290000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "ساتن",
    color: "کرم",
    rating: 4.7,
    reviews: 132,
    sold: 530,
    stock: 15,
    discount: 13,
  },
  {
    id: 4,
    name: "سرویس روتختی سه‌بعدی مدل گلستان",
    price: 4650000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "پنبه و پلی‌استر",
    color: "سفید و صورتی",
    rating: 4.9,
    reviews: 176,
    sold: 710,
    stock: 12,
    discount: 8.4,
  },
  {
    id: 5,
    name: "سرویس روتختی هتلی مدل لوکس",
    price: 5190000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی",
    size: "کینگ",
    material: "پنبه هتلی",
    color: "سفید",
    rating: 5.0,
    reviews: 203,
    sold: 845,
    stock: 10,
    discount: 10,
  },
  {
    id: 6,
    name: "سرویس روتختی کودک مدل ستاره",
    price: 1890000,
    image: "/images/models/1/Kiyan-V2-poi-n27_QM5.jpeg",
    category: "سرویس روتختی کودک",
    size: "یک‌نفره",
    material: "پنبه نرم",
    color: "آبی آسمانی",
    rating: 4.8,
    reviews: 84,
    sold: 390,
    stock: 20,
    discount: 15.6,
  },
];

export const newestSellsProduct = [
  {
    id: 1,
    name: "سرویس روتختی دونفره مدل رویال",
    price: 3850000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "پنبه ۱۰۰٪",
    color: "سفید و طوسی",
    rating: 4.9,
    reviews: 148,
    sold: 620,
    stock: 18,
    discount: 10,
  },
  {
    id: 2,
    name: "سرویس روتختی یک‌نفره مدل آرام",
    price: 2450000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی",
    size: "یک‌نفره",
    material: "میکروفایبر",
    color: "آبی",
    rating: 4.8,
    reviews: 95,
    sold: 480,
    stock: 24,
    discount: 11,
  },
  {
    id: 3,
    name: "سرویس روتختی دونفره مدل کلاسیک",
    price: 4290000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "ساتن",
    color: "کرم",
    rating: 4.7,
    reviews: 132,
    sold: 530,
    stock: 15,
    discount: 13,
  },
  {
    id: 4,
    name: "سرویس روتختی سه‌بعدی مدل گلستان",
    price: 4650000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی",
    size: "دونفره",
    material: "پنبه و پلی‌استر",
    color: "سفید و صورتی",
    rating: 4.9,
    reviews: 176,
    sold: 710,
    stock: 12,
    discount: 8.4,
  },
  {
    id: 5,
    name: "سرویس روتختی هتلی مدل لوکس",
    price: 5190000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی",
    size: "کینگ",
    material: "پنبه هتلی",
    color: "سفید",
    rating: 5.0,
    reviews: 203,
    sold: 845,
    stock: 10,
    discount: 10,
  },
  {
    id: 6,
    name: "سرویس روتختی کودک مدل ستاره",
    price: 1890000,
    image: "/images/models/beauty-desk/1.jpg",
    category: "سرویس روتختی کودک",
    size: "یک‌نفره",
    material: "پنبه نرم",
    color: "آبی آسمانی",
    rating: 4.8,
    reviews: 84,
    sold: 390,
    stock: 20,
    discount: 15.6,
  },
];